title: Ken Ohashi's personal page
email: will be updated later # ohashi.ken@isee.nagoya-u.ac.jp
# logo: /assets/img/logo.png
description: This is Ken Ohashi's personal web page.
# show_downloads: true
# google_analytics:
theme: jekyll-theme-minimal
